//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pubs_application.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pubsEntities : DbContext
    {
        public pubsEntities()
            : base("name=pubsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<author> authors { get; set; }
        public DbSet<employee> employees { get; set; }
        public DbSet<job> jobs { get; set; }
        public DbSet<pub_info> pub_info { get; set; }
        public DbSet<publisher> publishers { get; set; }
        public DbSet<sale> sales { get; set; }
        public DbSet<store> stores { get; set; }
        public DbSet<titleauthor> titleauthors { get; set; }
        public DbSet<title> titles { get; set; }
        public DbSet<discount> discounts { get; set; }
        public DbSet<roysched> royscheds { get; set; }
    }
}
